
export const BRAZILIAN_STATES = [
  { code: 'AC', name: 'Acre', ddd: ['68'] },
  { code: 'AL', name: 'Alagoas', ddd: ['82'] },
  { code: 'AP', name: 'Amapá', ddd: ['96'] },
  { code: 'AM', name: 'Amazonas', ddd: ['92', '97'] },
  { code: 'BA', name: 'Bahia', ddd: ['71', '73', '74', '75', '77'] },
  { code: 'CE', name: 'Ceará', ddd: ['85', '88'] },
  { code: 'DF', name: 'Distrito Federal', ddd: ['61'] },
  { code: 'ES', name: 'Espírito Santo', ddd: ['27', '28'] },
  { code: 'GO', name: 'Goiás', ddd: ['62', '64'] },
  { code: 'MA', name: 'Maranhão', ddd: ['98', '99'] },
  { code: 'MT', name: 'Mato Grosso', ddd: ['65', '66'] },
  { code: 'MS', name: 'Mato Grosso do Sul', ddd: ['67'] },
  { code: 'MG', name: 'Minas Gerais', ddd: ['31', '32', '33', '34', '35', '37', '38'] },
  { code: 'PA', name: 'Pará', ddd: ['91', '93', '94'] },
  { code: 'PB', name: 'Paraíba', ddd: ['83'] },
  { code: 'PR', name: 'Paraná', ddd: ['41', '42', '43', '44', '45', '46'] },
  { code: 'PE', name: 'Pernambuco', ddd: ['81', '87'] },
  { code: 'PI', name: 'Piauí', ddd: ['86', '89'] },
  { code: 'RJ', name: 'Rio de Janeiro', ddd: ['21', '22', '24'] },
  { code: 'RN', name: 'Rio Grande do Norte', ddd: ['84'] },
  { code: 'RS', name: 'Rio Grande do Sul', ddd: ['51', '53', '54', '55'] },
  { code: 'RO', name: 'Rondônia', ddd: ['69'] },
  { code: 'RR', name: 'Roraima', ddd: ['95'] },
  { code: 'SC', name: 'Santa Catarina', ddd: ['47', '48', '49'] },
  { code: 'SP', name: 'São Paulo', ddd: ['11', '12', '13', '14', '15', '16', '17', '18', '19'] },
  { code: 'SE', name: 'Sergipe', ddd: ['79'] },
  { code: 'TO', name: 'Tocantins', ddd: ['63'] }
];

export const CITIES_BY_STATE: Record<string, string[]> = {
  'AC': ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira', 'Tarauacá', 'Feijó'],
  'AL': ['Maceió', 'Arapiraca', 'Palmeira dos Índios', 'Rio Largo', 'Penedo'],
  'AP': ['Macapá', 'Santana', 'Laranjal do Jari', 'Oiapoque', 'Mazagão'],
  'AM': ['Manaus', 'Parintins', 'Itacoatiara', 'Manacapuru', 'Coari'],
  'BA': ['Salvador', 'Feira de Santana', 'Vitória da Conquista', 'Camaçari', 'Juazeiro', 'Ilhéus', 'Lauro de Freitas', 'Itabuna', 'Jequié', 'Teixeira de Freitas'],
  'CE': ['Fortaleza', 'Caucaia', 'Juazeiro do Norte', 'Maracanaú', 'Sobral', 'Crato', 'Itapipoca', 'Maranguape', 'Iguatu', 'Quixadá'],
  'DF': ['Brasília', 'Gama', 'Taguatinga', 'Ceilândia', 'Sobradinho'],
  'ES': ['Vitória', 'Vila Velha', 'Serra', 'Cariacica', 'Cachoeiro de Itapemirim', 'Linhares', 'São Mateus', 'Colatina', 'Guarapari', 'Aracruz'],
  'GO': ['Goiânia', 'Aparecida de Goiânia', 'Anápolis', 'Rio Verde', 'Luziânia', 'Águas Lindas de Goiás', 'Valparaíso de Goiás', 'Trindade', 'Formosa', 'Novo Gama'],
  'MA': ['São Luís', 'Imperatriz', 'São José de Ribamar', 'Timon', 'Caxias', 'Codó', 'Paço do Lumiar', 'Açailândia', 'Bacabal', 'Balsas'],
  'MT': ['Cuiabá', 'Várzea Grande', 'Rondonópolis', 'Sinop', 'Tangará da Serra', 'Cáceres', 'Sorriso', 'Lucas do Rio Verde', 'Barra do Garças', 'Primavera do Leste'],
  'MS': ['Campo Grande', 'Dourados', 'Três Lagoas', 'Corumbá', 'Ponta Porã', 'Naviraí', 'Nova Andradina', 'Sidrolândia', 'Maracaju', 'Aquidauana'],
  'MG': ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora', 'Betim', 'Montes Claros', 'Ribeirão das Neves', 'Uberaba', 'Governador Valadares', 'Ipatinga'],
  'PA': ['Belém', 'Ananindeua', 'Santarém', 'Marabá', 'Parauapebas', 'Castanhal', 'Abaetetuba', 'Cametá', 'Marituba', 'Bragança'],
  'PB': ['João Pessoa', 'Campina Grande', 'Santa Rita', 'Patos', 'Bayeux', 'Sousa', 'Cajazeiras', 'Cabedelo', 'Guarabira', 'Monteiro'],
  'PR': ['Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa', 'Cascavel', 'São José dos Pinhais', 'Foz do Iguaçu', 'Colombo', 'Guarapuava', 'Paranaguá'],
  'PE': ['Recife', 'Jaboatão dos Guararapes', 'Olinda', 'Bandeira do Sul', 'Caruaru', 'Petrolina', 'Paulista', 'Cabo de Santo Agostinho', 'Camaragibe', 'Garanhuns'],
  'PI': ['Teresina', 'Parnaíba', 'Picos', 'Piripiri', 'Floriano', 'Campo Maior', 'Barras', 'Altos', 'Oeiras', 'Pedro II'],
  'RJ': ['Rio de Janeiro', 'São Gonçalo', 'Duque de Caxias', 'Nova Iguaçu', 'Niterói', 'Belford Roxo', 'São João de Meriti', 'Campos dos Goytacazes', 'Petrópolis', 'Volta Redonda'],
  'RN': ['Natal', 'Mossoró', 'Parnamirim', 'São Gonçalo do Amarante', 'Macaíba', 'Ceará-Mirim', 'Caicó', 'Assu', 'Currais Novos', 'Santa Cruz'],
  'RS': ['Porto Alegre', 'Caxias do Sul', 'Pelotas', 'Canoas', 'Santa Maria', 'Gravataí', 'Viamão', 'Novo Hamburgo', 'São Leopoldo', 'Rio Grande'],
  'RO': ['Porto Velho', 'Ji-Paraná', 'Ariquemes', 'Vilhena', 'Cacoal', 'Rolim de Moura', 'Guajará-Mirim', 'Jaru', 'Ouro Preto do Oeste', 'Buritis'],
  'RR': ['Boa Vista', 'Rorainópolis', 'Caracaraí', 'Alto Alegre', 'Mucajaí', 'Cantá', 'Bonfim', 'Normandia', 'São João da Baliza', 'São Luiz'],
  'SC': ['Florianópolis', 'Joinville', 'Blumenau', 'São José', 'Criciúma', 'Chapecó', 'Itajaí', 'Lages', 'Palhoça', 'Balneário Camboriú'],
  'SP': ['São Paulo', 'Guarulhos', 'Campinas', 'São Bernardo do Campo', 'Santo André', 'Osasco', 'Ribeirão Preto', 'Sorocaba', 'Mauá', 'São José dos Campos'],
  'SE': ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto', 'Itabaiana', 'São Cristóvão', 'Estância', 'Tobias Barreto', 'Simão Dias', 'Propriá', 'Capela'],
  'TO': ['Palmas', 'Araguaína', 'Gurupi', 'Porto Nacional', 'Paraíso do Tocantins', 'Colinas do Tocantins', 'Guaraí', 'Tocantinópolis', 'Miracema do Tocantins', 'Dianópolis']
};
