// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pocynpbouhtlkhcryopn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvY3lucGJvdWh0bGtoY3J5b3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTcxNjgsImV4cCI6MjA2MTU5MzE2OH0.fi1wgAOkYDYNk7RDOqpxcyCE8ppKkV1Zgbv0JeFzG-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});